[build]
command = "pip install -r requirements.txt && gunicorn app:app"
functions = "netlify/functions"
publish = "."

[dev]
framework = "#custom"
command = "python app.py"

[build.environment]
PYTHON_VERSION = "3.9"

[[redirects]]
from = "/*"
to = "/.netlify/functions/app"
status = 200
force = true 