[build]
command = """
pip install -r requirements.txt
python app.py
"""
publish = "."

[build.environment]
PYTHON_VERSION = "3.8"

[[redirects]]
from = "/*"
to = "/.netlify/functions/app"
status = 200
force = true 